"""
This is a setup.py script altered from one generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

# A custom plist for letting it associate with all files.
Plist = dict(CFBundleDocumentTypes= [dict(CFBundleTypeExtensions=["*"],
                                          #CFBundleTypeName="kUTTypeText", # this should be text files, but I'm not sure the details.
                                          CFBundleTypeRole="Editor"),
                                    ]
             )


APP = ['MacApp.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, # this puts the names of dropped files into sys.argv when starting the app. 
           'iconfile': 'MacAppIcon.icns',
           'plist': Plist, 
           }


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
